{{
  exports.publishOn = new Date().toISOString();
}}

PATCH http://localhost:3000/posts/123 HTTP/1.1
Content-Type: application/json

{
  "id": 12,
  "title": "What's new with NestJS updated",
  "publishOn": "{{publishOn}}",
  "tags": [1,2]
}